---
# See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199 and
# https://github.com/geerlingguy/ansible-role-java/issues/64
- name: Ensure 'man' directory exists.
  ansible.builtin.file: # noqa risky-file-permissions
    path: /usr/share/man/man1
    state: directory
    mode: "0755"
    recurse: true
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version | int >= 18

- name: Download gpg keys and erlang repository
  block:
    - name: Download gpg keys for erlang repository updated
      ansible.builtin.apt_key:
        id: E495BB49CC4BBE5B
        url: "{{ erlang_apt_gpg_url }}"
        keyring: /etc/apt/trusted.gpg.d/erlang-E495BB49CC4BBE5B.gpg

    - name: Ensure erlang updated repository is configured
      ansible.builtin.apt_repository:
        repo: "{{ erlang_apt_repository }}"
        state: present

- name: Add rabbitmq apt and keys and repository
  block:
    - name: Download gpg keys for rabbitmq-server repository
      ansible.builtin.apt_key:
        id: 9F4587F226208342
        url: "{{ rabbitmq_apt_gpg_url }}"
        keyring: /etc/apt/trusted.gpg.d/rabbitmq-9F4587F226208342.gpg

    - name: Ensure rabbitmq-server repository is configured
      ansible.builtin.apt_repository:
        repo: "{{ rabbitmq_apt_repository }}"
        state: present

- name: Ensure erlang is installed.
  ansible.builtin.package:
    name: erlang
    state: present

- name: Ensure RabbitMQ is installed.
  ansible.builtin.apt:
    name: rabbitmq-server={{ rabbitmq_version }}-1
    state: present
