---
- name: Converge
  hosts: all
  #become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Add python3-debian
      when: ansible_os_family == 'Debian'
      apt:
        name: [python3-debian]

  roles:
    - role: geerlingguy.rabbitmq
